config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :orderdetails
  post 'orders/create'
  namespace :admin do
    resources :items
  end
  root to: 'items#index'

  get '/carts', to: 'carts#index'
  post '/carts', to: 'carts#create'
  put '/carts/:id', to: 'carts#update'
  delete '/carts', to: 'carts#destroy'
  resources :items

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/order_detail.rb
# frozen_string_literal: true

class OrderDetail < ApplicationRecord
  belongs_to :order
end

app/controllers/orderdetails_controller.rb
# frozen_string_literal: true

class OrderdetailsController < ApplicationController
  before_action :basic_auth

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    @order_sum_quantity = @order.sum_quantity
    @promotion_code = PromotionCode.find_by(order_id: @order.id)
  end

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |name, password|
      name == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end
end

app/helpers/orderdetails_helper.rb
# frozen_string_literal: true

module OrderdetailsHelper
end

app/views/orderdetails/index.html.slim
section.py-5
  .container.px-2.px-lg-5
    h1 購入明細一覧
    table.table
      thead
        tr
          th[scope="col"]
            | 注文ID
          th[scope="col"]
            | 購入者氏名
          th[scope="col"]
            | 注文日付
          th[scope="col"]
            | 
      tbody
        - @orders.each do |order|
          tr
            td
              = order.id
            td
              = "#{order.user.firstname} #{order.user.lastname}"
            td
              = order.user.created_at.in_time_zone('Tokyo')
            td
              = link_to '詳細', orderdetail_path(order), class: 'btn btn-outline-dark mt-auto'

app/views/orderdetails/show.html.slim
section.py-5
  .container.px-2.px-lg-5
    h1 購入明細

    h2 購入者情報

    table.table
      thead
        tr
          th[scope="col"]
            | 項目
          th[scope="col"]
            | 登録情報
      tbody
        tr
          td
            | 氏名(ユーザー名)
          td
            = "#{@order.user.firstname} #{@order.user.lastname}（#{@order.user.username}）"
        tr
          td
            | メールアドレス
          td
            = @order.user.email
        tr
          td
            | 郵便番号
          td
            = @order.user.zip
        tr
          td
            | 国
          td
            = @order.user.country
        tr
          td
            | 都道府県
          td
            = @order.user.state
        tr
          td
            | 住所１
          td
            = @order.user.address
        tr
          td
            | 住所２
          td
            = @order.user.address2

    h2 注文商品情報
    table.table
      thead
        tr
          th[scope="col"]
            | 商品名
          th[scope="col"]
            | 金額
          th[scope="col"]
            | 注文個数
          th[scope="col"]
            | 
      tbody
        - @order.order_details.each do |order_detail|
          tr
            td
              = order_detail.name
            td
              = "#{order_detail.price}円"
            td
              = "#{order_detail.quantity}個"
            td
        - if @promotion_code.present?
          tr
            td.text-success
              = "プロモーションコード (#{@promotion_code.code})"
            td.text-success
              = "-#{@promotion_code.educed_price}円"
            td.text-success
              | -
            td
    div.text-end
      = "総合計金額 #{@promotion_code.present? ? @order.sum_price - @promotion_code.educed_price : @order.sum_price}円"

    = link_to '一覧に戻る', orderdetails_path, class: 'btn btn-outline-dark mt-auto'