config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :orderdetails
  post 'orders/create'
  namespace :admin do
    resources :items
  end
  root to: 'items#index'

  get '/carts', to: 'carts#index'
  post '/carts', to: 'carts#create'
  put '/carts/:id', to: 'carts#update'
  delete '/carts', to: 'carts#destroy'
  resources :items

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  has_many :cart_items, dependent: :delete_all
  has_many :carts, through: :cart_items

  has_one_attached :image
  validates :name, presence: true
  validates :price, presence: true, numericality: true
  validates :description, presence: true
end

app/controllers/admin/items_controller.rb
# frozen_string_literal: true

module Admin
  class ItemsController < ApplicationController
    before_action :basic_auth

    def index
      @items = Item.with_attached_image.order(:id)
    end

    def new
      @item = Item.new
    end

    def create
      @item = Item.new(item_params)

      if @item.save
        flash[:notice] = "商品名「#{@item.name}」を登録しました。"
        redirect_to admin_items_url
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @item = Item.find(params[:id])
    end

    def update
      @item = Item.find(params[:id])
      if @item.update(item_params)
        flash[:notice] = "商品名「#{@item.name}」を更新しました。"
        redirect_to admin_items_url
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      item = Item.find(params[:id])
      item.destroy
      flash[:notice] = "商品名「#{item.name}」を削除しました。"
      redirect_to admin_items_url
    end

    private

    def item_params
      params.require(:item).permit(:name, :price, :description, :image)
    end

    def basic_auth
      authenticate_or_request_with_http_basic do |name, password|
        name == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
      end
    end
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  def index
    @items = Item.with_attached_image.order(:id)
  end

  def show
    @item = Item.with_attached_image.find(params[:id])
    @items = Item.with_attached_image.limit(4).where.not(id: params[:id]).order(created_at: :desc)
  end
end

app/helpers/admin/items_helper.rb
# frozen_string_literal: true

module Admin
  module ItemsHelper
  end
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
end

app/views/admin/items/_form.html.slim
container.px-4.px-lg-5.mx-5
  - if @item.errors.present?
    ul#error_explanation
      - @item.errors.full_messages.each do |message|
        li= message

= form_with model: item, local: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'item_name'
  .form-group
    = f.label :price
    = f.text_field :price, class: 'form-control', id: 'item_price'
  .form-group
    = f.label :description
    = f.text_area :description, rows: 5, class: 'form-control', id: 'item_description'
  .form-group
    = f.label :image
    = f.file_field :image, class: 'form-control'
  = f.submit nil, class: 'btn btn-dark'

= link_to '戻る', admin_items_path, class: 'btn btn-outline-dark mt-auto'

app/views/admin/items/edit.html.slim
.container
  h1 商品編集
  = render partial: 'form', locals: { item: [:admin, @item] }

app/views/admin/items/index.html.slim
section
  .container.px-4.px-lg-5.mt-5
    h1 管理ページ 商品一覧
    = link_to '商品作成', new_admin_item_path, class: 'btn btn-outline-dark mt-auto'

    .row
      - @items.each do |item|
          .col-4.mb-5
            .card.h-100
              = image_tag item.image, class: 'card-img-top' if item.image.attached?
              .card-body.p-4
                .text-center
                  h5.fw-bolder
                    = item.name 
                  = "#{item.price}円"
              .card-footer.p-4.pt-0.border-top-0.bg-transparent
                .text-center
                  = link_to '編集', edit_admin_item_path(item), class: 'btn btn-outline-dark mt-auto'
                  = button_to '削除', { :action => 'destroy', :id => item.id }, { method: :delete, class: 'btn btn-danger'}

app/views/admin/items/new.html.slim
.container
  h1 商品作成
  = render partial: 'form', locals: { item: [:admin, @item] }