config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :orderdetails
  post 'orders/create'
  namespace :admin do
    resources :items
  end
  root to: 'items#index'

  get '/carts', to: 'carts#index'
  post '/carts', to: 'carts#create'
  put '/carts/:id', to: 'carts#update'
  delete '/carts', to: 'carts#destroy'
  resources :items

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :items, through: :cart_items
  has_one :cart_promotion_code, dependent: :destroy
  has_one :promotion_code, through: :cart_promotion_code
  def sum_price
    cart_items.inject(0) { |result, cart_item| result + cart_item.item.price }
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  def index
    @cart_detail = @cart_items.group(:item_id).count

    @items = Item.where(id: @cart_detail.keys)
    @all_price = @cart.sum_price
    @all_price -= @cart.promotion_code.educed_price if @cart.promotion_code.present? && @cart.cart_items.size.positive?
    @order = Order.new
  end

  def new; end

  def create
    @item = Item.find(params[:item_id])
    add_count = params[:count] ? params[:count].to_i : 1
    add_cart_item = (1..add_count).map do
      @cart.cart_items.build(item_id: @item.id)
    end
    CartItem.import add_cart_item
    redirect_to root_path
  end

  def update
    code_detail = PromotionCode.find_by(code: params[:code], used_at: nil)

    if code_detail.nil?
      flash[:alert] = '入力されたコードはすでに使用済みか、正しくないコードです'
    else
      cart_used_code = CartPromotionCode.find_by(promotion_code_id: code_detail.id)
      if cart_used_code.present?
        flash[:alert] = '入力されたコードはすでに使用済みです'
      else
        @cart.build_cart_promotion_code(promotion_code_id: code_detail.id)
        @cart.cart_promotion_code.save
      end
    end
    redirect_to carts_path
  end

  def destroy
    destroy_item = @cart_items.where(item_id: params[:item_id])
    destroy_item.destroy_all
    redirect_to carts_path
  end
end

app/views/carts/create.html.slim
h1 Sessions#create
p Find me in app/views/sessions/create.html.slim

app/views/carts/index.html.slim
  head
    title
      | 購入 - 私の通販サイト
    link[rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/checkout/"]
    link[href="../assets/dist/css/bootstrap.min.css" rel="stylesheet"]
    style
      |  .bd-placeholder-img { font-size: 1.125rem; text-anchor: middle; -webkit-user-select: none; -moz-user-select: none; user-select: none; } @media (min-width: 768px) { .bd-placeholder-img-lg { font-size: 3.5rem; } } .b-example-divider { width: 100%; height: 3rem; background-color: rgba(0, 0, 0, .1); buser: solid rgba(0, 0, 0, .15); buser-width: 1px 0; box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15); } .b-example-vr { flex-shrink: 0; width: 1.5rem; height: 100vh; } .bi { vertical-align: -.125em; fill: currentColor; } .nav-scroller { position: relative; z-index: 2; height: 2.75rem; overflow-y: hidden; } .nav-scroller .nav { display: flex; flex-wrap: nowrap; padding-bottom: 1rem; margin-top: -1px; overflow-x: auto; text-align: center; white-space: nowrap; -webkit-overflow-scrolling: touch; } .btn-bd-primary { --bd-violet-bg: #712cf9; --bd-violet-rgb: 112.520718, 44.062154, 249.437846; --bs-btn-font-weight: 600; --bs-btn-color: var(--bs-white); --bs-btn-bg: var(--bd-violet-bg); --bs-btn-buser-color: var(--bd-violet-bg); --bs-btn-hover-color: var(--bs-white); --bs-btn-hover-bg: #6528e0; --bs-btn-hover-buser-color: #6528e0; --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb); --bs-btn-active-color: var(--bs-btn-hover-color); --bs-btn-active-bg: #5a23c8; --bs-btn-active-buser-color: #5a23c8; } .bd-mode-toggle { z-index: 1500; } 
    link[href="checkout/checkout.css" rel="stylesheet"]
  body.bg-body-tertiary
    svg[xmlns="http://www.w3.org/2000/svg" style="display: none;"]
      symbol#check2[viewbox="0 0 16 16"]
        path[d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"]
      symbol#circle-half[viewbox="0 0 16 16"]
        path[d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"]
      symbol#moon-stars-fill[viewbox="0 0 16 16"]
        path[d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"]
        path[d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"]
      symbol#sun-fill[viewbox="0 0 16 16"]
        path[d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"]
    .dropdown.position-fixed.bottom-0.end-0.mb-3.me-3.bd-mode-toggle
      button#bd-theme.btn.btn-bd-primary.py-2.dropdown-toggle.d-flex.align-items-center[type="button" aria-expanded="false" data-bs-toggle="dropdown" aria-label="Toggle theme (auto)"]
        svg.bi.my-1.theme-icon-active[width="1em" height="1em"]
          use[href="#circle-half"]
        span#bd-theme-text.visually-hidden
          | Toggle theme
      ul.dropdown-menu.dropdown-menu-end.shadow[aria-labelledby="bd-theme-text"]
        li
          button.dropdown-item.d-flex.align-items-center[type="button" data-bs-theme-value="light" aria-pressed="false"]
            svg.bi.me-2.opacity-50.theme-icon[width="1em" height="1em"]
              use[href="#sun-fill"]
            |  Light 
            svg.bi.ms-auto.d-none[width="1em" height="1em"]
              use[href="#check2"]
        li
          button.dropdown-item.d-flex.align-items-center[type="button" data-bs-theme-value="dark" aria-pressed="false"]
            svg.bi.me-2.opacity-50.theme-icon[width="1em" height="1em"]
              use[href="#moon-stars-fill"]
            |  Dark 
            svg.bi.ms-auto.d-none[width="1em" height="1em"]
              use[href="#check2"]
        li
          button.dropdown-item.d-flex.align-items-center.active[type="button" data-bs-theme-value="auto" aria-pressed="true"]
            svg.bi.me-2.opacity-50.theme-icon[width="1em" height="1em"]
              use[href="#circle-half"]
            |  Auto 
            svg.bi.ms-auto.d-none[width="1em" height="1em"]
              use[href="#check2"]
    .container
      main
        .py-5.text-center
          h2
            | 購入手続き
        .row.g-5
          .col-md-5.col-lg-4.order-md-last
            h4.d-flex.justify-content-between.align-items-center.mb-3
              span.text-primary
                | カート内容
              span.badge.bg-primary.rounded-pill
                = @cart_items.nil? ? 0 : @cart_items.count
            ul.list-group.mb-3
              - @items.each do |item|
                li.list-group-item.d-flex.justify-content-between.lh-sm
                  div
                    h6.my-0
                      = "#{item.name}"
                    small.text-body-secondary
                      = item.description
                  span.text-body-secondary
                    = "#{item.price}円 * #{@cart_detail[item.id]}個"
                  = button_to '削除', { controller: 'carts', action: 'destroy' }, { method: :delete, params: { item_id: item.id }, class: 'btn btn-danger mt-auto' }
              - if @cart.cart_items.size > 0 && !(@cart.promotion_code.nil?)
                li.list-group-item.d-flex.justify-content-between.bg-body-tertiary
                  div.text-success
                    h6.my-0
                      | プロモコード
                    small
                      = @cart.promotion_code.code
                  span.text-success
                    = "-#{@cart.promotion_code.educed_price}円"
              li.list-group-item.d-flex.justify-content-between
                span
                  | 合計金額
                strong
                  = "#{@all_price}円"
            = form_with url: { controller: 'carts', action: 'update', id: @cart.id }, method: :put, class: 'card p-2', local: true do |f|
              .input-group
                = f.text_field :code, class: 'form-control', placeholder: "sample1"
                = f.submit 'コード適用', class: 'btn btn-secondary'
          .col-md-7.col-lg-8
            h4.mb-3
              | 購入者情報
            = form_with url: orders_create_path(@order), method: :post, local: true do |f|
              = f.fields_for :user do |user|
                .row.g-3
                  .col-sm-6
                    = user.label :firstname
                    = user.text_field :firstname, class: 'form-control', placeholder: '太郎', id: 'user_firstname'
                    .invalid-feedback
                      |  Valid first name is required. 
                  .col-sm-6
                    = user.label :lastname
                    = user.text_field :lastname, class: 'form-control', placeholder: '田中', id: 'user_lastname'
                    .invalid-feedback
                      |  Valid last name is required. 
                  .col-12
                    = user.label :username
                    .input-group.has-validation
                      span.input-group-text
                        | @
                      = user.text_field :username, class: 'form-control', placeholder: 'username', id: 'user_username'
                      .invalid-feedback
                        |  Your username is required. 
                  .col-12
                    = user.label :email
                    = user.text_field :email, class: 'form-control', placeholder: 'email@example.com', id: 'user_email'
                    .invalid-feedback
                      |  Please enter a valid email address for shipping updates. 
                  .col-12
                    = user.label :address
                    = user.text_field :address, class: 'form-control', placeholder: '千代田区千代田', id: 'user_address'
                    .invalid-feedback
                      |  Please enter your shipping address. 
                  .col-12
                    = user.label :address2
                    span.text-body-secondary
                      | (Optional)
                    = user.text_field :address2, class: 'form-control', placeholder: '1-1', id: 'user_address2'
                    = user.label :country
                    = user.text_field :country, class: 'form-control', placeholder: '日本', id: 'user_country'
                    .invalid-feedback
                      |  Please select a valid country. 
                  .col-md-4
                    = user.label :state
                    = user.text_field :state, class: 'form-control', placeholder: '東京都', id: 'user_state'
                    .invalid-feedback
                      |  Please provide a valid state. 
                  .col-md-3
                    = user.label :zip
                    = user.text_field :zip, class: 'form-control', placeholder: '1000001', id: 'user_zip'
                    .invalid-feedback
                      |  Zip code required. 
                hr.my-4
                h4.mb-3
                  | 支払い情報
                .row.gy-3
                  .col-md-6
                    = user.label :cardname
                    = user.text_field :cardname, class: 'form-control', id: 'user_cardname'
                    small.text-body-secondary
                      | Full name as displayed on card
                    .invalid-feedback
                      |  Name on card is required 
                  .col-md-6
                    = user.label :creditcardnumber
                    = user.text_field :creditcardnumber, class: 'form-control', id: 'user_creditcardnumber'
                    .invalid-feedback
                      |  Credit card number is required 
                  .col-md-3
                    = user.label :expiration
                    = user.text_field :expiration, class: 'form-control', id: 'user_expiration'
                    .invalid-feedback
                      |  Expiration date required 
                  .col-md-3
                    = user.label :cvv
                    = user.text_field :cvv, class: 'form-control', id: 'user_cvv'
                    .invalid-feedback
                      |  Security code required 
              hr.my-4
                = f.submit '購入する', class: 'w-100 btn btn-primary btn-lg'
        footer.my-5.pt-5.text-body-secondary.text-center.text-small

          li.list-inline-item
            a[href="#"]
              | Privacy
          li.list-inline-item
            a[href="#"]
              | Terms
          li.list-inline-item
            a[href="#"]
              | Support
        script[src="../assets/dist/js/bootstrap.bundle.min.js"]
        script[src="checkout.js"]

app/views/carts/ne_w.html.slim
| <!doctype html> 
html[lang="en" data-bs-theme="auto"]
  head
    script[src="../assets/js/color-modes.js"]
    meta[charset="utf-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1"]
    meta[name="description" content=""]
    meta[name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors"]
    meta[name="generator" content="Hugo 0.112.5"]
    title
      | Checkout example · Bootstrap v5.3
    link[rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/checkout/"]
    = button_to new_user_path, method: :get do
      i.fas.fa-user
      |  ユーザー登録 
    link[href="../assets/dist/css/bootstrap.min.css" rel="stylesheet"]
    style
      |  .bd-placeholder-img { font-size: 1.125rem; text-anchor: middle; -webkit-user-select: none; -moz-user-select: none; user-select: none; } @media (min-width: 768px) { .bd-placeholder-img-lg { font-size: 3.5rem; } } .b-example-divider { width: 100%; height: 3rem; background-color: rgba(0, 0, 0, .1); border: solid rgba(0, 0, 0, .15); border-width: 1px 0; box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15); } .b-example-vr { flex-shrink: 0; width: 1.5rem; height: 100vh; } .bi { vertical-align: -.125em; fill: currentColor; } .nav-scroller { position: relative; z-index: 2; height: 2.75rem; overflow-y: hidden; } .nav-scroller .nav { display: flex; flex-wrap: nowrap; padding-bottom: 1rem; margin-top: -1px; overflow-x: auto; text-align: center; white-space: nowrap; -webkit-overflow-scrolling: touch; } .btn-bd-primary { --bd-violet-bg: #712cf9; --bd-violet-rgb: 112.520718, 44.062154, 249.437846; --bs-btn-font-weight: 600; --bs-btn-color: var(--bs-white); --bs-btn-bg: var(--bd-violet-bg); --bs-btn-border-color: var(--bd-violet-bg); --bs-btn-hover-color: var(--bs-white); --bs-btn-hover-bg: #6528e0; --bs-btn-hover-border-color: #6528e0; --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb); --bs-btn-active-color: var(--bs-btn-hover-color); --bs-btn-active-bg: #5a23c8; --bs-btn-active-border-color: #5a23c8; } .bd-mode-toggle { z-index: 1500; } 
    link[href="checkout.css" rel="stylesheet"]
  body.bg-body-tertiary
    svg[xmlns="http://www.w3.org/2000/svg" style="display: none;"]
      symbol#check2[viewbox="0 0 16 16"]
        path[d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"]
      symbol#circle-half[viewbox="0 0 16 16"]
        path[d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"]
      symbol#moon-stars-fill[viewbox="0 0 16 16"]
        path[d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"]
        path[d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"]
      symbol#sun-fill[viewbox="0 0 16 16"]
        path[d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"]
    .dropdown.position-fixed.bottom-0.end-0.mb-3.me-3.bd-mode-toggle
      button#bd-theme.btn.btn-bd-primary.py-2.dropdown-toggle.d-flex.align-items-center[type="button" aria-expanded="false" data-bs-toggle="dropdown" aria-label="Toggle theme (auto)"]
        svg.bi.my-1.theme-icon-active[width="1em" height="1em"]
          use[href="#circle-half"]
        span#bd-theme-text.visually-hidden
          | Toggle theme
      ul.dropdown-menu.dropdown-menu-end.shadow[aria-labelledby="bd-theme-text"]
        li
          button.dropdown-item.d-flex.align-items-center[type="button" data-bs-theme-value="light" aria-pressed="false"]
            svg.bi.me-2.opacity-50.theme-icon[width="1em" height="1em"]
              use[href="#sun-fill"]
            |  Light 
            svg.bi.ms-auto.d-none[width="1em" height="1em"]
              use[href="#check2"]
        li
          button.dropdown-item.d-flex.align-items-center[type="button" data-bs-theme-value="dark" aria-pressed="false"]
            svg.bi.me-2.opacity-50.theme-icon[width="1em" height="1em"]
              use[href="#moon-stars-fill"]
            |  Dark 
            svg.bi.ms-auto.d-none[width="1em" height="1em"]
              use[href="#check2"]
        li
          button.dropdown-item.d-flex.align-items-center.active[type="button" data-bs-theme-value="auto" aria-pressed="true"]
            svg.bi.me-2.opacity-50.theme-icon[width="1em" height="1em"]
              use[href="#circle-half"]
            |  Auto 
            svg.bi.ms-auto.d-none[width="1em" height="1em"]
              use[href="#check2"]
    .container
      main
        .py-5.text-center
          img.d-block.mx-auto.mb-4[src="../assets/brand/bootstrap-logo.svg" alt="" width="72" height="57"]
          h2
            | Checkout form
          p.lead
            | Below is an example form built entirely with Bootstrap’s form controls. Each required form group has a validation state that can be triggered by attempting to submit the form without completing it.
        .row.g-5
          .col-md-5.col-lg-4.order-md-last
            h4.d-flex.justify-content-between.align-items-center.mb-3
              span.text-primary
                | Your cart
              span.badge.bg-primary.rounded-pill
                | 3
        ul.list-group.mb-3

        li.list-group-item.d-flex.justify-content-between.lh-sm
          div

        h6.my-0
          | Product name
        small.text-body-secondary
          | Brief description
    span.text-body-secondary
      | $12
    li.list-group-item.d-flex.justify-content-between.lh-sm
      div
        h6.my-0
          | Second product
        small.text-body-secondary
          | Brief description
      span.text-body-secondary
        | $8
    li.list-group-item.d-flex.justify-content-between.lh-sm
      div
        h6.my-0
          | Third item
        small.text-body-secondary
          | Brief description
      span.text-body-secondary
        | $5
    li.list-group-item.d-flex.justify-content-between.bg-body-tertiary
      .text-success
        h6.my-0
          | Promo code
        small
          | EXAMPLECODE
      span.text-success
        | −$5
    li.list-group-item.d-flex.justify-content-between
      span
        | Total (USD)
      strong
        | $20
    form.card.p-2
      .input-group
        input.form-control[type="text" placeholder="Promo code"]
        button.btn.btn-secondary[type="submit"]
          | Redeem
    .col-md-7.col-lg-8
      h4.mb-3
        | Billing address
      form.needs-validation[novalidate]
        .row.g-3
          .col-sm-6
            label.form-label[for="firstName"]
              | First name
            input#firstName.form-control[type="text" placeholder="" value="" required]
            .invalid-feedback
              |  Valid first name is required. 
          .col-sm-6
            label.form-label[for="lastName"]
              | Last name
            input#lastName.form-control[type="text" placeholder="" value="" required]
            .invalid-feedback
              |  Valid last name is required. 
          .col-12
            label.form-label[for="username"]
              | Username
            .input-group.has-validation
              span.input-group-text
                | @
              input#username.form-control[type="text" placeholder="Username" required]
              .invalid-feedback
                |  Your username is required. 
          .col-12
            label.form-label[for="email"]
              | Email 
              span.text-body-secondary
                | (Optional)
            input#email.form-control[type="email" placeholder="you@example.com"]
            .invalid-feedback
              |  Please enter a valid email address for shipping updates. 
          .col-12
            label.form-label[for="address"]
              | Address
            input#address.form-control[type="text" placeholder="1234 Main St" required]
            .invalid-feedback
              |  Please enter your shipping address. 
          .col-12
            label.form-label[for="address2"]
              | Address 2 
              span.text-body-secondary
                | (Optional)
            input#address2.form-control[type="text" placeholder="Apartment or suite"]
          .col-md-5
            label.form-label[for="country"]
              | Country
            select#country.form-select[required]
              option[value=""]
                | Choose...
              option
                | United States
            .invalid-feedback
              |  Please select a valid country. 
          .col-md-4
            label.form-label[for="state"]
              | State
            select#state.form-select[required]
              option[value=""]
                | Choose...
              option
                | California
            .invalid-feedback
              |  Please provide a valid state. 
          .col-md-3
            label.form-label[for="zip"]
              | Zip
            input#zip.form-control[type="text" placeholder="" required]
            .invalid-feedback
              |  Zip code required. 
        hr.my-4
        .form-check
          input#same-address.form-check-input[type="checkbox"]
          label.form-check-label[for="same-address"]
            | Shipping address is the same as my billing address
        .form-check
          input#save-info.form-check-input[type="checkbox"]
          label.form-check-label[for="save-info"]
            | Save this information for next time
        hr.my-4
        h4.mb-3
          | Payment
        .my-3
          .form-check
            input#credit.form-check-input[name="paymentMethod" type="radio" checked required]
            label.form-check-label[for="credit"]
              | Credit card
          .form-check
            input#debit.form-check-input[name="paymentMethod" type="radio" required]
            label.form-check-label[for="debit"]
              | Debit card
          .form-check
            input#paypal.form-check-input[name="paymentMethod" type="radio" required]
            label.form-check-label[for="paypal"]
              | PayPal
        .row.gy-3
          .col-md-6
            label.form-label[for="cc-name"]
              | Name on card
            input#cc-name.form-control[type="text" placeholder="" required]
            small.text-body-secondary
              | Full name as displayed on card
            .invalid-feedback
              |  Name on card is required 
          .col-md-6
            label.form-label[for="cc-number"]
              | Credit card number
            input#cc-number.form-control[type="text" placeholder="" required]
            .invalid-feedback
              |  Credit card number is required 
          .col-md-3
            label.form-label[for="cc-expiration"]
              | Expiration
            input#cc-expiration.form-control[type="text" placeholder="" required]
            .invalid-feedback
              |  Expiration date required 
          .col-md-3
            label.form-label[for="cc-cvv"]
              | CVV
            input#cc-cvv.form-control[type="text" placeholder="" required]
            .invalid-feedback
              |  Security code required 
        hr.my-4
        button.w-100.btn.btn-primary.btn-lg[type="submit"]
          | Continue to checkout
    footer.my-5.pt-5.text-body-secondary.text-center.text-small
      p.mb-1
        | &copy; 2017–2023 Company Name
      ul.list-inline

      li.list-inline-item
        a[href="#"]
          | Privacy
      li.list-inline-item
        a[href="#"]
          | Terms
      li.list-inline-item
        a[href="#"]
          | Support
    script[src="../assets/dist/js/bootstrap.bundle.min.js"]
    script[src="checkout.js"]