config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :orderdetails
  post 'orders/create'
  namespace :admin do
    resources :items
  end
  root to: 'items#index'

  get '/carts', to: 'carts#index'
  post '/carts', to: 'carts#create'
  put '/carts/:id', to: 'carts#update'
  delete '/carts', to: 'carts#destroy'
  resources :items

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  has_many :cart_items, dependent: :delete_all
  has_many :carts, through: :cart_items

  has_one_attached :image
  validates :name, presence: true
  validates :price, presence: true, numericality: true
  validates :description, presence: true
end

app/controllers/admin/items_controller.rb
# frozen_string_literal: true

module Admin
  class ItemsController < ApplicationController
    before_action :basic_auth

    def index
      @items = Item.with_attached_image.order(:id)
    end

    def new
      @item = Item.new
    end

    def create
      @item = Item.new(item_params)

      if @item.save
        flash[:notice] = "商品名「#{@item.name}」を登録しました。"
        redirect_to admin_items_url
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @item = Item.find(params[:id])
    end

    def update
      @item = Item.find(params[:id])
      if @item.update(item_params)
        flash[:notice] = "商品名「#{@item.name}」を更新しました。"
        redirect_to admin_items_url
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      item = Item.find(params[:id])
      item.destroy
      flash[:notice] = "商品名「#{item.name}」を削除しました。"
      redirect_to admin_items_url
    end

    private

    def item_params
      params.require(:item).permit(:name, :price, :description, :image)
    end

    def basic_auth
      authenticate_or_request_with_http_basic do |name, password|
        name == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
      end
    end
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  def index
    @items = Item.with_attached_image.order(:id)
  end

  def show
    @item = Item.with_attached_image.find(params[:id])
    @items = Item.with_attached_image.limit(4).where.not(id: params[:id]).order(created_at: :desc)
  end
end

app/helpers/admin/items_helper.rb
# frozen_string_literal: true

module Admin
  module ItemsHelper
  end
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
end

app/views/items/_list.html.slim
- items.each do |item|
    .col.mb-5
      .card.h-100
        = image_tag item.image, class: 'card-img-top' if item.image.attached?
        .card-body.p-4
          .text-center
            h5.fw-bolder
              = item.name 
            = "#{item.price}円"
        .card-footer.p-4.pt-0.border-top-0.bg-transparent
          .text-center
            = link_to '詳細', item_path(item), class: 'btn btn-outline-dark mt-auto'
            = button_to 'カート追加', { controller: 'carts', action: 'create' }, { method: :post, params: { item_id: item.id }, class: 'btn btn-outline-dark mt-auto' }

app/views/items/index.html.slim
    header.bg-dark.py-5
      .container.px-4.px-lg-5.my-5
        .text-center.text-white
          h1.display-4.fw-bolder
            | 私の通販サイト
          p.lead.fw-normal.text-white-50.mb-0
            | 売ります
    section.py-5
      .container.px-4.px-lg-5.mt-5
        .row.gx-4.gx-lg-5.row-cols-2.row-cols-md-3.row-cols-xl-4.justify-content-center
          = render partial: 'list', locals: { items: @items }

app/views/items/show.html.slim
    section.py-5
      .container.px-4.px-lg-5.my-5
        .row.gx-4.gx-lg-5.align-items-center
          .col-md-6
            / img.card-img-top.mb-5.mb-md-0[src="https://dummyimage.com/600x700/dee2e6/6c757d.jpg" alt="..."]
            = image_tag @item.image, class: 'card-img-top mb-5 mb-md-0' if @item.image.attached?

          .col-md-6
          
            .small.mb-1
              | SKU: BST-498
            h1.display-5.fw-bolder
              = @item.name
            .fs-5.mb-5
              span
                = "#{@item.price}円"
            p.lead
              = @item.description
            .d-flex
              = form_with url: { controller: 'carts', action: 'create' } do |f| 
                = f.number_field :count, { min: 1, class: 'form-control text-center me-3 num-field-3rem' }
                = f.button :submit, name: 'item_id', value: @item.id , class: 'btn btn-outline-dark flex-shrink-0' do
                  i.bi-cart-fill.me-1
                  | カートに追加 
    section.py-5.bg-light
      .container.px-4.px-lg-5.mt-5
        h2.fw-bolder.mb-4
          | Related products
        .row.gx-4.gx-lg-5.row-cols-2.row-cols-md-3.row-cols-xl-4.justify-content-center
          = render partial: 'list', locals: { items: @items }